// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_stellar = "CgkIja6x2owHEAIQBw"; // <GPGSID>
        public const string achievement_space_guppy = "CgkIja6x2owHEAIQDw"; // <GPGSID>
        public const string leaderboard_total_score = "CgkIja6x2owHEAIQDg"; // <GPGSID>
        public const string leaderboard_top_score = "CgkIja6x2owHEAIQAQ"; // <GPGSID>
        public const string achievement_advanced = "CgkIja6x2owHEAIQBg"; // <GPGSID>
        public const string achievement_experienced = "CgkIja6x2owHEAIQCw"; // <GPGSID>
        public const string achievement_beginner = "CgkIja6x2owHEAIQBQ"; // <GPGSID>
        public const string achievement_homesick = "CgkIja6x2owHEAIQDA"; // <GPGSID>
        public const string achievement_veteran = "CgkIja6x2owHEAIQCQ"; // <GPGSID>
        public const string achievement_newbie = "CgkIja6x2owHEAIQCg"; // <GPGSID>
        public const string achievement_legendary = "CgkIja6x2owHEAIQCA"; // <GPGSID>

}

